// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ62WgYNxO14xvP_swrPIWdWPB68OGd1A',
    appId: '1:195343532619:web:81492b649a0c580fa5c3ce',
    messagingSenderId: '195343532619',
    projectId: 'tiktok-clone-7a8fe',
    authDomain: 'tiktok-clone-7a8fe.firebaseapp.com',
    storageBucket: 'tiktok-clone-7a8fe.appspot.com',
    measurementId: 'G-DBY4EL11SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbXey0ByQTHIJdFckh1lb8iO0nH1SJ_Z0',
    appId: '1:195343532619:android:f75eadc89bf8d6fba5c3ce',
    messagingSenderId: '195343532619',
    projectId: 'tiktok-clone-7a8fe',
    storageBucket: 'tiktok-clone-7a8fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG1YLqAZBEDIpMIlm9jK_d74pmgYOAEEo',
    appId: '1:195343532619:ios:62a0800cde4f1af4a5c3ce',
    messagingSenderId: '195343532619',
    projectId: 'tiktok-clone-7a8fe',
    storageBucket: 'tiktok-clone-7a8fe.appspot.com',
    iosClientId: '195343532619-96ijdvvtikhgsmm2j3ll4f9okhvsksrv.apps.googleusercontent.com',
    iosBundleId: 'co.nomadcoders.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG1YLqAZBEDIpMIlm9jK_d74pmgYOAEEo',
    appId: '1:195343532619:ios:a267f28e74389af0a5c3ce',
    messagingSenderId: '195343532619',
    projectId: 'tiktok-clone-7a8fe',
    storageBucket: 'tiktok-clone-7a8fe.appspot.com',
    iosClientId: '195343532619-esrnfe2fph3v3edh51nhjiam2m0uib56.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
